### ISSUE TITLE
Missing instructions on how to mix moonshine into this to create a karsk.

### ISSUE THREAD

**Issue by haavamoa** [andmos/Coffee#5]
Not sure what a karsk is? Read about it [here](https://en.wikipedia.org/wiki/Karsk)

**Comment by bpjohannessen** [comment]
I don't think think this is a real issue. Coffee is not supposed to be mixed with karsk.

**Comment by haavamoa** [comment]
Who said anyhthing about mixing coffee and karsk? :o Coffee + moonshine = karsk

**Comment by andmos** [comment]
After careful testing we found out that the Aeropress is the best way to mix real good Trøndersk Karsk. As a starter, use [Coop Blå](https://coop.no/merkevarer/dagligvare/coop-kaffe/coop-kaffe-produkter/coop-kaffe-fyldig--aromatisk/) for a roundt and good taste.
